### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by aure**

### CODE REVIEW

**Comment by morekid** [comment]
Thanks Aure, many interesting points from your rework. Checking out.

**Comment by morekid** [comment]
@aure is there a specific reason why envelope and waveform changes are tied to note changes? I can see many use cases for changing an envelope within the same note, much like in real analog synthesis. Is it some underlying logic in csound? or is AudioKit architecture?

Any way around it that you can think of?

Other than that I really appreciate you taking the time to review and update this, the changes you made gave me valuable hints on how AudioKit works and where to go next.

**Comment by aure** [comment]
It's very easy to fake a continuous update by stopping and starting a note immediately so it's not much of an issue but csound works using tables, and a note sticks the table in memory and constantly reads from it.  To swap out the table for another one is unpredictable and has performance implications.  So tables are usually considered constants over the lifetime of a note.  It's not a practical limitation, most just a different philosophical approach than you may be used to in analog.   I can look into implementing an oscillator that does not have this limitation but with VCO I doubt this will ever change.  Really if you want flexibility, probably should be using the AKOscillator with tables instead of the VCO.

**Comment by morekid** [comment]
I see, I will try that then and thanks for taking the time to explain this, valuable information.

**Pull request merged**
